//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Authentication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Market.Authentication.Properties.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;https://fonts.googleapis.com/css?family=Tangerine&quot;&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Droid+Sans|Lora:400,400i,700,700i&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;style&gt;
        ///	* {
        ///		margin: 0px;
        ///		padding: 0px;
        ///	}
        ///	body {
        ///	    background-color: #7D3C98;
        ///	    color: #fff;
        ///	    font-family: &apos;Lora&apos;, serif;
        ///        font-size: 24px;
        ///	}
        ///	div.container {
        ///		display: inline-block;
        ///	    position: fixed;
        ///	    top: 0;
        ///	    bottom: 0;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountAlreadyVerifiedPage {
            get {
                return ResourceManager.GetString("AccountAlreadyVerifiedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;&lt;!--[if IE]&gt;&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; class=&quot;ie-browser&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;&lt;![endif]--&gt;&lt;!--[if !IE]&gt;&lt;!--&gt;&lt;html style=&quot;margin: 0;padding: 0;&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;!--&lt;![endif]--&gt;&lt;head&gt;
        ///    &lt;!--[if gte mso 9]&gt;&lt;xml&gt;
        ///     &lt;o:OfficeDocumentSettings&gt;
        ///      &lt;o:AllowPNG/&gt;
        ///      &lt;o:PixelsPerI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountVerificationEmail {
            get {
                return ResourceManager.GetString("AccountVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;https://fonts.googleapis.com/css?family=Tangerine&quot;&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Droid+Sans|Lora:400,400i,700,700i&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;style&gt;
        ///	* {
        ///		margin: 0px;
        ///		padding: 0px;
        ///	}
        ///	body {
        ///	    background-color: #CB4335;
        ///	    color: #fff;
        ///	    font-family: &apos;Lora&apos;, serif;
        ///        font-size: 24px;
        ///	}
        ///	div.container {
        ///		display: inline-block;
        ///	    position: fixed;
        ///	    top: 0;
        ///	    bottom: 0;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountVerificationErrorPage {
            get {
                return ResourceManager.GetString("AccountVerificationErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;https://fonts.googleapis.com/css?family=Tangerine&quot;&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Droid+Sans|Lora:400,400i,700,700i&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;style&gt;
        ///	* {
        ///		margin: 0px;
        ///		padding: 0px;
        ///	}
        ///	body {
        ///	    background-color: #3f51b5;
        ///	    color: #fff;
        ///	    font-family: &apos;Lora&apos;, serif;
        ///        font-size: 24px;
        ///	}
        ///	div.container {
        ///		display: inline-block;
        ///	    position: fixed;
        ///	    top: 0;
        ///	    bottom: 0;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountVerifiedPage {
            get {
                return ResourceManager.GetString("AccountVerifiedPage", resourceCulture);
            }
        }
    }
}
