//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.WebApis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Market.WebApis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gmpatel@live.com.
        /// </summary>
        internal static string FromEmail {
            get {
                return ResourceManager.GetString("FromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cm#80Gm#78.
        /// </summary>
        internal static string FromEmailPassword {
            get {
                return ResourceManager.GetString("FromEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsureMe.
        /// </summary>
        internal static string FromName {
            get {
                return ResourceManager.GetString("FromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-access-key.
        /// </summary>
        internal static string KeyHeaderKey1 {
            get {
                return ResourceManager.GetString("KeyHeaderKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string KeyHeaderKey2 {
            get {
                return ResourceManager.GetString("KeyHeaderKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yPvEzaYUyBn1X3wftTH7G64GZHl3DmVW9/rQ47j1rKBAYXT6z914hwNYhSTHsSxtIXoRGzJHP3Q5/a2tEjG8MXmWAr7PoqUgM7N5ARF6Hn9rEfVO94o1OTfawn12pYzaCodzcACQcwqLPkjizKiKFu+cGsObDJWJh60Nvf1Sf9DZ4ugTG0E5itPWmli2jNbfUOEz7wgpzMOFKJZDDawchVEFt8YpWXWn4SEZbD1Y7Z8sDOrV9+tJUXUHfUOoxYzWzTKvUjJ1q2owxfQD46wIozTy4DYUVqTEtG4SZHtwVP44q/IZ6J9vYQLydljUfCMZKmCxnBQJka8u1tE5aERgCGqPvLYYkR8YtNcE2XAzBtyx8vYl+c+PGkqP85vZkLctviMFIqJLn4w0Il9zy9skoU2nlxzAK+3uts/nk5LITHRrbKCZ55mckdBtPt6n5jh2Bxy7Nl4zApTvGl99WFv6hOu660n8Ebj63vEe38MXVog=.
        /// </summary>
        internal static string MasterToken1 {
            get {
                return ResourceManager.GetString("MasterToken1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9Z9kSTTxPozpWybSqXjjPSzO9lloABHpY5wgDrqBSHP3dpC74Vx4KF3WKNpdBcVx0A7DNOEsHFxZ6VLc0XI9CaHHYaeRl/5nLOpUg8MZz8KvdcOh/mhJnR49Za7vgO9NV+e+cQOdmDD8nSPivLDmmJ6MIkwLDrRUmsHFLouo+hEgw7BnxDR7FY+owVrj6kAh+5CQ/sTCP7cpPKpukBS/NWzh4el9Czw0v+OjCA3Q8hd0/2QaSW+GIuV6rcwh6msnsYKEL8XkVXZQm9gKKmay0DL3BQx1KIqRFAdPXkPcv14lg9UOUcmj5LRxzUjPsXERceipNXWFk+qxrxuXqff6mG3hmUqMt23l8X5WP2Qup7gRnI/F4YN3/gSAehgmje5/Eu46nQl15biP0BSTGMDZYj+SBnZXDG13ZeQnRKTWRSvqWVTCAJOto+t9md3pcLmSWgo3KYYaC81Qu0BWdws3NQsnHDhhG/y4xFGDpDU2mg8=.
        /// </summary>
        internal static string MasterToken2 {
            get {
                return ResourceManager.GetString("MasterToken2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.live.com.
        /// </summary>
        internal static string SMTPServer {
            get {
                return ResourceManager.GetString("SMTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-access-token.
        /// </summary>
        internal static string TokenHeaderKey1 {
            get {
                return ResourceManager.GetString("TokenHeaderKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        internal static string TokenHeaderKey2 {
            get {
                return ResourceManager.GetString("TokenHeaderKey2", resourceCulture);
            }
        }
    }
}
